### ISSUE TITLE
Support for '--user' option

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad-driver-podman#10]
Please implement support for `user` option: https://www.nomadproject.io/docs/job-specification/task.html#user

This is useful to select user for running a command inside container (e.g. `podman run --user=nobody --init --rm docker.io/library/debian:stable whoami`).

Thanks.

**Comment by onlyjob** [comment]
Docker driver supports that: https://www.nomadproject.io/docs/drivers/docker.html#pids_limit:

> Additionally, the docker driver supports customization of the container's user through the task's [user option](https://www.nomadproject.io/docs/job-specification/task.html#user).

**Comment by towe75** [comment]
See latest commit. It includes the feature, a readme snipped and a unit test. Please check.
