### ISSUE TITLE
build: current Vagrant machine fails to provision

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad-driver-podman#107]
Provisioning error:
```
The following packages have unmet dependencies:
    podman-linux:  podman : Depends: crun (>= 100:0.19.1-1) but it is not going to be installed
    podman-linux:           Recommends: fuse-overlayfs but it is not going to be installed
```

**Comment by towe75** [comment]
It's a misalignment between GH action runner and box OS. We switched here recently to ubuntu 20.04, see #106 
Vagrant starts a ubuntu 18.04 box and tries to install podman from the wrong repository.

I suggest to bump the Vagrantfile ubuntu version.
