### ISSUE TITLE
Unable to run task: invalid config provided: namespace mode path requires a value

### ISSUE THREAD

**Issue by rnovacek** [hashicorp/nomad-driver-podman#111]
I'm trying to use podman with nomad to run some containers. I'm very new to nomad, so it can definitely be a problem between keyboard and chair.

I'm trying to run this simple job:
```
job "nextcloud" {
  datacenters = ["dc1"]

  group "nextcloud" {
    network {
      mode = "bridge"

      port "redis" {
        to = 6379
      }
    }

    task "redis" {
      driver = "podman"

      config {
        image = "redis:3.2"
        ports = ["redis"]
      }
    }
  }
}
```

And I'm getting following error:
```
2021-05-07T00:16:44.616+0200 [ERROR] client.alloc_runner.task_runner: running driver failed: alloc_id=69fcb974-90d2-fa9c-4b70-6e6f45f82488 task=redis error="rpc error: code = Unknown desc = failed to start task, could not create container: unknown error, status code: 500: {"cause":"namespace mode path requires a value","message":"invalid config provided: namespace mode path requires a value","response":500}
```

Some info about my system:
Fedora 33 x86_64
Podman 3.1.0
Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)

Started the agent in dev mode:
```
sudo nomad agent -dev -bind 0.0.0.0 -log-level DEBUG -data-dir /opt/nomad/data/
```

Only changes I did (if I remember correctly) was:
* download nomad-driver-podman to `/opt/nomad/data/plugins/nomad-driver-podman`
* symlink `/usr/libexec/cni` to `/opt/cni/bin` to get bridge network running (not sure if that's good way to do it) - the /usr/libexec/cni is from `containernetworking-plugins-0.9.1-2.fc33.x86_64` package

**Comment by rnovacek** [comment]
Thank you, using `network_mode` in `config` instead of `mode` in `network` did the trick. The error is pretty confusing though, but it's up to the devs if they want to fix it :) Feel free to close this.

**Comment by jrasell** [comment]
Closing this issue as it has been resolved by configuration changes. Please feel free to reopen if you believe there is still an issue, or open a new issue linking to this.
