### ISSUE TITLE
Docker Registry Auth

### ISSUE THREAD

**Issue by ahjohannessen** [hashicorp/nomad-driver-podman#132]
Is it possible to configure a credentials file for podman to use. Similar to how docker auth can be configured:

```
    config {
        auth {
            config = "/path/to/docker/creds/file"
        }
    }
```
containing something like:

```
{
	"auths": {
		"docker.io": {
			"auth": "erfi7sYi89234xJUqaqxgmzcnQ2rRFWM5aJX0EC="
		},
		"quay.io": {
			"auth": "juQAqGmz5eR1ipzx8Evn6KGdw8fEa1w5MWczmgY="
		}
	}
}
```

podman itself supports `--authfile=path` and `REGISTRY_AUTH_FILE` env, it seems.

**Comment by shoenig** [comment]
I think implementing support for creds like the docker driver should be possible now? At least the docker pull API supports identity tokens, https://docs.podman.io/en/latest/_static/api.html#tag/images/operation/ImagePullLibpod

```
base-64 encoded auth config. Must include the following four values: username, password, email and server address OR simply just an identity token.
```

I'll take a look into making it work.
