### ISSUE TITLE
selinux_opts attribute support

### ISSUE THREAD

**Issue by gjpin** [hashicorp/nomad-driver-podman#135]
Hi,

First of all, thank you for your work on this driver.

I would like to know if there are plans to add the selinux_opts attribute (podman's --security-opt flag), as it's supported by [libpod's API](https://docs.podman.io/en/latest/_static/api.html#operation/ContainerCreateLibpod).

It would be very helpful to be able to use custom SELinux policies on specific containers.

Thanks!

**Comment by lgfa29** [comment]
Fixed in #139. Thanks @gjpin!
