### ISSUE TITLE
Support for volume_mount stanza

### ISSUE THREAD

**Issue by towe75** [hashicorp/nomad-driver-podman#146]
See discussion/post at https://discuss.hashicorp.com/t/nomad-support-for-mounted-volumes-with-podman/29234/2

The driver should have support for the [volume_mount](https://www.nomadproject.io/docs/job-specification/volume_mount) stanza to simplify host/group volume usage.

It's quite simple to workaround the lack of volume_mount by leveraging the regular volume stanza at the task level. But the documentation is not clear on that either.

**Comment by qubidt** [comment]
Is this addressed by #152?

**Comment by towe75** [comment]
@qubidt : yes, it is. Closing in favour of #152

**Comment by qubidt** [comment]
That PR is still unmerged, so not sure if it's appropriate to close this ticket yet. Happy to see it's getting resolved tho
