### ISSUE TITLE
Release 0.4.0?

### ISSUE THREAD

**Issue by jdoss** [hashicorp/nomad-driver-podman#162]
`main` currently has support for privileged containers. That would be super helpful for my workloads.

**Comment by jdoss** [comment]
Thanks @shoenig! 

On a side note, I did build from `main` and tried it out on the Nomad 1.3.0 beta and it was pretty unstable (memory and CPU stats not polling from containers, containers crashing after a bit). I am not sure when you folks want to update Nomad in the driver, but that might be a landmine down the road.

**Comment by jdoss** [comment]
Any chance if we can't get a 0.4.0 release but a 0.3.x point release to unblock us from using Nomad 1.3.1? Having to manually build everything is a chore.

**Comment by svenstaro** [comment]
@shoenig Ping. There hasn't been a release in a year. I think this is quite important for Hashicorp to show continued support of this driver.

**Comment by quinndiggity** [comment]
> Hi @jdoss we're right in the middle of a mass migration of our release pipelines; we should be able to get a `0.4.0` release in the next couple of weeks.

@shoenig, just following up on this; would be great to not require building this driver in order for the documentation at https://www.nomadproject.io/plugins/drivers/podman to be accurate

**Comment by lgfa29** [comment]
Hi all, we're still coordinating a few things, but we should get a new release out soon. Thanks for the patience and apologies for the delay!

**Comment by lgfa29** [comment]
Hi all 👋 

Release 0.4.0 is now available 🎉 
https://releases.hashicorp.com/nomad-driver-podman/0.4.0/

Thanks for the patience 😄
