### ISSUE TITLE
Nomad 1.3.1 incompatible with v0.3.0 due to config

### ISSUE THREAD

**Issue by hoh** [hashicorp/nomad-driver-podman#170]
# Problem

After upgrading to Nomad 1.3.1 with nomad-driver-podman v0.3.0, a job would not start anymore due to the following error message:

```
Type: Failed Validation
Description:  3 errors occurred: * failed to parse config: * Invalid label: No argument or block type is named "auth". * Invalid label: No argument or block type is named "force_pull". 
```

The configuration that causes the issue is in the form:
```python
    task "app" {
      driver = "podman"
      config {
        image = "registry.host.com/group/app:branch"
        force_pull = true
        auth {
          username = "host+deploy-token-1234"
          password = "verysecret"
        }
        ports = ["http"]
        volumes = [
        ]
      }
    }
```

# Diagnostic

It appears that when using Nomad 1.3.1 (and 1.3.0 ?) with v0.3.0 of nomad-driver-podman, the fields `auth` and `force_pull` of the task are not recognized.

# Resolution

Upgrading to a new build from the main branch ( dadc09fa02eb10acc09e33462243ab023f6d2599 ) appears to fix the issue.

Publishing a new release and encouraging Nomad 1.3.1 users to use that new release would prevent them from facing this issue.

# Annexes

Related to "Release 0.4.0? #162"

Screenshot of the error in the UI:
![image](https://user-images.githubusercontent.com/404665/169822111-6d250027-3298-413e-8476-cea7535381ea.png)

**Comment by adamdox** [comment]
I'm having the same problem with the `logging` block. Unable to start an allocation with a logging section defined.

**Comment by michaelerickson** [comment]
I have the same issue as @adamdox. I have a job specification that works just fine until I add a `logging` stanza in the `task | config`

The documentation implies that this should work. If it doesn't - then should either kick it out of the documentation or make a new release.

I do not see the same problem as @hoh regarding the `auth` attribute. My `task | config` has an `auth` with both `username` and `password` and that works just fine.

**Comment by svenstaro** [comment]
I have the problem that I get 0 logging from any containers. Logs are just completely empty.

**Comment by lgfa29** [comment]
Hi everyone 👋 

v0.4.0 is now available (https://releases.hashicorp.com/nomad-driver-podman/0.4.0/) would mind checking if it solves the problems?

Thank you.

**Comment by shoenig** [comment]
Like @lgfa29 mentioned please file a bug if you are still experiencing an issue with 0.4.0+

**Comment by atomlab** [comment]
> I have the problem that I get 0 logging from any containers. Logs are just completely empty.

I have the same problem. 
```
# podman  logs my_container
#
```

Nomad v1.2.2
Nomad Podman Driver 0.4.0
Podman 3.4.4
