### ISSUE TITLE
Add armhf to nightly builds

### ISSUE THREAD

**Issue by quinndiggity** [hashicorp/nomad-driver-podman#178]
While pending on https://github.com/hashicorp/nomad-driver-podman/issues/162 builds from `master` are necessary - alternatively the nightly builds can be used, however these lack `armhf` (only `arm64` + `amd64`), so until the release is cut there's no avoiding building from source for this driver.

**Comment by lgfa29** [comment]
Hi @quinndiggity 👋 

#180 adds `arm` as one of the build architectures. We don't actively test for it, but updating our build pipeline now will add it to the niightly builds where you can test it. 

If the nightly builds work well we can keep for the next final release.

**Comment by quinndiggity** [comment]
much appreciated!
