### ISSUE TITLE
Create a fix release with #182

### ISSUE THREAD

**Issue by quentin9696** [hashicorp/nomad-driver-podman#197]
Hi, 

I've been stuck during 2 days with some weird issue on container stop. 
After few research, I realized that the PR #182 fix the issue but is not yet publish with podman api >= 4.1.1. We must use the nightly artifact which can be unstable on a prod context. 
I also realized I'm not alone in this issue (https://github.com/hashicorp/nomad/issues/14880)

Can we trigger a release v0.4.1 to take at least a blocking bug fix? This can cause some headache to other user who use OS like Fedora CoreOS who already updgrade to 4.1.1+ podman api version

**Comment by lgfa29** [comment]
Version [0.4.1](https://releases.hashicorp.com/nomad-driver-podman/0.4.1/) has now been released. Thank you for the ping 🙂

**Comment by quentin9696** [comment]
Thank you for the release :)
