### ISSUE TITLE
Support for bridge networking

### ISSUE THREAD

**Issue by adam-stanek** [hashicorp/nomad-driver-podman#20]
Hello,

does this driver support bridge networking? Nomad fails to schedule any jobs with:

```
task "whatever" {
  ...
  group "whatever" {
    network {
      mode = "bridge"
    }
    ...
  }
}
```

Saying: `Unable to add allocation due to error: failed to configure network manager: task whatever does not support "bridge" networking mode`.

I am not sure if I should be looking for the culprit in nomad, podman or this driver.

The same job definition works when I use docker driver (with CNI installed).

Thanks for the info.

**Comment by towe75** [comment]
Hi,

brige mode is not supported yet. 
I will have a look at it, so let's keep this issue open.

**Comment by towe75** [comment]
Hey,

i am a bit unsure how to approach this. Maybe it would be a good idea to start mapping a task group onto a podman pod. It should make sharing namespaces/resources simpler and it seems to fit.

@onlyjob  maybe you want to share some idea?

**Comment by onlyjob** [comment]
I did not have a chance to think about implementation...

**Comment by towe75** [comment]
@adam-stanek see #33 . Bridge is the default networking mode for rootful containers but soon you will be able to use "host" and "none" as well.
