### ISSUE TITLE
problem releasing stopped containers

### ISSUE THREAD

**Issue by benbourner** [hashicorp/nomad-driver-podman#201]
Hello, i have a critical issue that is preventing moving forward with the current approach. We are testing a nomad environment with podman instead of docker (which we have running very successfully and stably). In our podman environment, containers happily start and work just fine, but when they are stopped, nomad is seemingly only partially aware. Simply launching a job, then trying to stop it leaves it permanently hanging in this state:
Killing | Sent interrupt. Waiting 5s before force killing
However, looking deeper, the container is actually completely stopped in podman.
Struggling to diagnose this problem further. Where could I look deeper to help diagnose this?

**Comment by benbourner** [comment]
I realise i'm running into the same issue as others. Sorry for the duplicate.

**Comment by quentin9696** [comment]
Hi @benbourner, 

See #197

A release 0.4.1 shoud comes

**Comment by lgfa29** [comment]
Version [0.4.1 is now avaiable](https://releases.hashicorp.com/nomad-driver-podman/0.4.1/) which includes a fix for this. I'm going to close this for now but please give it a try and let us know if the problem still persists 🙂
