### ISSUE TITLE
Can we get an updated release for 0.5?

### ISSUE THREAD

**Issue by jdoss** [hashicorp/nomad-driver-podman#216]
@lgfa29 Can we get 0.5 released? There are a lot of fixes that are being built in the nightly right now and the GH Action just broke for some reason tonight which only produced an ARM64 artifact.

**Comment by jdoss** [comment]
I'd settle for 0.4.2 if the point release is too much. The mount propagation fixes are what my nomad jobs crave.

**Comment by lgfa29** [comment]
Hi @jdoss 👋 

Yeah, we're long due for a release. I will wait for https://github.com/hashicorp/nomad-driver-podman/pull/218 to be reviewed and merged then I will release v0.4.2.

I will then merge https://github.com/hashicorp/nomad-driver-podman/pull/209 as a breaking change and release v0.5.0 right afterwards, how does that sound?

**Comment by jdoss** [comment]
Sounds good to me @lgfa29. I look forward to it :)

**Comment by lgfa29** [comment]
Sorry for the delay, but [v0.4.2](https://releases.hashicorp.com/nomad-driver-podman/0.4.2/) is out now 🎉 

It turns out that we could implement #209  in a backwards compatible way, so a breaking change was not required.

**Comment by jdoss** [comment]
Thanks @lgfa29! You are the best! 😄
