### ISSUE TITLE
panic: failed to lookup nobody user: user: unknown user nobody

### ISSUE THREAD

**Issue by jdoss** [hashicorp/nomad-driver-podman#228]
It looks like we are hitting the same issue that happened in https://github.com/hashicorp/nomad/issues/14737 where the nomad-driver-podman isn't respecting NSS to look up users.

I am running into this issue on Fedora CoreOS 37.20230303.3.0

```bash
# /etc/nomad/plugins/nomad-driver-podman
panic: failed to lookup nobody user: user: unknown user nobody

goroutine 1 [running]:
github.com/hashicorp/nomad/helper/users.init.0()
	github.com/hashicorp/nomad@v1.5.2/helper/users/lookup_unix.go:37 +0x1b4
# id nobody
uid=99(nobody) gid=99(nobody) groups=99(nobody)
```

**Comment by shoenig** [comment]
I think this might be due to building the driver with `CGO_ENABLED=0`, where the pure-Go implementation of the standard library `users` package only reads from `/etc/passwd` - and (IIUC) Fedora CoreOS externalizes the `nobody` user to an nss lookup.

**Comment by jdoss** [comment]
Ahhhh yep. That makes sense. Here's what I am seeing on my end.

Plugin from releases.hashicorp.com
```bash
file /etc/nomad/plugins/nomad-driver-podman 
/etc/nomad/plugins/nomad-driver-podman: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=tA-nyhXEkFEKjKMCrbWV/9xjUPy06QVQ82b4TatHu/Ra2CBcZm5LKHkBrSQw8R/30CfM25FK3BlHy4UB_3X, with debug_info, not stripped
```

Plugin that I compiled and tested while looking into #227
```bash
$ file build/nomad-driver-podman
build/nomad-driver-podman: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=c35039ea25dc9a6adf735a8b4710fc75ee51b6f6, for GNU/Linux 3.2.0, with debug_info, not stripped
```

Can we build the driver with `CGO_ENABLED=1` or is there a pure go way to look up uses using NSS? https://go.dev/src/net/nss.go maybe?

**Comment by shoenig** [comment]
> Can we build the driver with CGO_ENABLED=1

Yeah I think that's the most reasonable thing to do - it's what we do for the `nomad` binary itself as well. I plan on digging into Podman work in the next few weeks, I'll add this to my list of things to do.

**Comment by shoenig** [comment]
There might be a way to fix this without resorting to building with CGO. The podman driver itself doesn't need any of the code which is causing a problem here - but rather it's being invoked as an `init` block of a package being transitively imported.

```
➜ go mod why github.com/hashicorp/nomad/helper/users
# github.com/hashicorp/nomad/helper/users
github.com/hashicorp/nomad-driver-podman
github.com/hashicorp/nomad/plugins/drivers
github.com/hashicorp/nomad/client/allocdir
github.com/hashicorp/nomad/helper/users
```

Let me see if we can play some musical chairs with these packages and eliminate that transitive dependency.
