### ISSUE TITLE
Rootless in combination with rootful

### ISSUE THREAD

**Issue by skoppe** [hashicorp/nomad-driver-podman#284]
I really like running workload in rootless containers.

However, I have not found a way to have both rootless and rootful containers on a single nomad node.

Because some things do need rootful containers, CSI plugins being one example, I see no alternative than switching to rootful.

Is there anything I am not aware about?

**Comment by skoppe** [comment]
I think something discussed in https://github.com/hashicorp/nomad-driver-podman/issues/84#issuecomment-1004325468 would make sense.

**Comment by lgfa29** [comment]
Hi @skoppe 👋 

Thank you for the suggestion, I think that would be a very interesting feature.

Unfortunately, as the comment you link points out, this would be a very heave lift to implement, but I have placed this into our board for further roadmaping and triagging.

**Comment by ygersie** [comment]
Wouldn’t it be be possible to make the plugin name configurable and declare it twice in the config? Meaning one could spin up a job with:
```hcl
driver = "podman"
```
Or
```hcl
driver = "podman-rootless"
```

**Comment by skoppe** [comment]
> Wouldn’t it be be possible to make the plugin name configurable and declare it twice in the config? Meaning one could spin up a job with

Yes, I have done exactly that.

It would be great if Nomad can jump on this rootless bandwagon and support it out of the box. Right not I am blocked on things like sidecars and csi mounts not working, and have to run those tasks as rootless.
