### ISSUE TITLE
shm_size under config is not recognized

### ISSUE THREAD

**Issue by aristeidist** [hashicorp/nomad-driver-podman#305]
I am trying to define shm size under config as it is required by the software vendor as: 1GB

a podman run equivalent is in my case : podman run -d -u 982 -p 8080:8080 -p 55555:55555 --shm-size=1g......._all the other arguments..._.
and works great in the command line under the user id specified.

So entering the same in nomad under config like:

```
config {
shm_size = "12910212"
}
```

 **Invalid label: No argument or block type is named "shm_size".** 

I have tried no quotes as well it appears it doesn't recognize it.

Is there some way around this? I have been looking everywhere - at this stage even a default for SHM would be sufficient for me.

Thank you in advance.

**Comment by shoenig** [comment]
Hi @aristeidist I believe we would simply need to add `shm_size` as something the Nomad Podman driver config parsing expects and pass the value on to podman. Do you want to give it a try and open a PR? Otherwise we can take care of it.

**Comment by aristeidist** [comment]
Hello, thank you for the reply - it would be great if this was implemented - it is actually preventing me from using a Redhat/Podman/Nomad combination rootless or not.

**Comment by rjthomas013** [comment]
Hi @shoenig, I think I have a branch ready with the fix, could you please give me access to push the branch so that I can raise a PR.
