### ISSUE TITLE
Podman does not pull newest image from registry

### ISSUE THREAD

**Issue by OneOfTheJohns** [hashicorp/nomad-driver-podman#399]
Hi,

Im running nomad-podman env with versions:
Nomad v1.8.1
podman version 5.1.1

On a Freebsd host.

If i start a nomad job, that would create containers on a different node, podman would pull that image, start the container and everything is cool at this step, but when i push new image to container registry with the same name, re-run the nomad job (stop it, purge, start the job again), it seems that the image is not getting re-pulled. Not sure if im missing any configuration, or that is a bug.

**Comment by ruspaul013** [comment]
Hello @OneOfTheJohns 

Did you add this in the task configuration?
```
config {
  force_pull = true
}
```

**Comment by OneOfTheJohns** [comment]
Guh, my bad, i guess i have thought it would be set to true by default... Thank you @ruspaul013 .
