### ISSUE TITLE
no STDOUT/STDERR

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad-driver-podman#4]
`STDOUT` and `STDERR` are not visible in Nomad.

Something like the following config demonstrates that the output is going nowhere and no log appears in the _alloc_ directory:

~~~~
config {
    image = "docker.io/library/debian:stable"
    command = "/bin/echo"
    args = [ "4444" ]
}
~~~~

**Comment by towe75** [comment]
Thank you for the feedback, i'll look into it.

**Comment by towe75** [comment]
Check my latest commit. Now the podman log should be forwarded into the nomad logging facility. It's thus also visible in the nomad web ui and of course accessible via nomad alloc logs. Again there is a small unit test and a hint in the readme. 
I did not explicitely check stderr handling but i assume that it will be included in the podman log output by default.

**Comment by onlyjob** [comment]
This is much better now and I can see STDOUT in Nomad log. Thanks.

However STDERR is not quite working as expected. Consider the following example:

```
command = "/bin/sh"
args = [ "-c", "hostname >&2; echo test"]
```

Nomad show output of both commands in Logs/stdout while Logs/stderr is empty.

The command line reproducer would be something like

    podman run -t --rm docker.io/library/debian:stable /bin/sh -c "hostname >&2; echo test" 2>>/dev/null

The above command also prints the output of both commands to STDOUT because Podman apparently redirects STDERR-->STDOUT when option `-t` is given.

The following command (without `-t`) works as expected:

    podman run --rm docker.io/library/debian:stable /bin/sh -c "hostname >&2; echo test" 2>>/dev/null

Therefore I suspect that driver starts Podman with equivalent of `-t` which mixes STDOUT and STDERR together.

**Comment by towe75** [comment]
Thank you for the hints, i will give it another try.

**Comment by towe75** [comment]
@onlyjob I'm a bit unsure about the "right" approach, so i filed a question into podmans issue tracker.

**Comment by drewbailey** [comment]
@towe75 I think there is mention of this in #37 but we currently don't have STDERR logging, we ultimately will likely need something like [docker logger](https://github.com/hashicorp/nomad/blob/master/drivers/docker/docklog/docker_logger.go) to stream logs from containers to alloc fifos
