### ISSUE TITLE
FSIsolation capabilities

### ISSUE THREAD

**Issue by drewbailey** [hashicorp/nomad-driver-podman#52]
Currently we support none, or at least fingerprint as so https://github.com/hashicorp/nomad-driver-podman/blob/master/driver.go#L70.

Look into supporting `FSIsolationImage`, it may be as minimal of a change as changing the fingerprint value.

**Comment by tgross** [comment]
Fixed as of https://github.com/hashicorp/nomad-driver-podman/commit/b580f2d1874273bd61640525d54a02e3747c2df4
