### ISSUE TITLE
Nomad seems to be publishing wrong port to Consul

### ISSUE THREAD

**Issue by volfco** [hashicorp/nomad-driver-podman#61]
I'm running an nginx container that listens internally on port 80. Here's my task:

```hcl
    task "nginx" {
      driver = "podman"
      config {
        image = ".../telescope-frontend:3559d7c273ca"
        port_map = {
          http = 80
        }
      }

      env { }

      resources {
        cpu    = 1000  # MHz
        memory = 512  # MB

        network {
          port "http" {}
        }
      }
```

It works as expected. The container spawns and the service is published. But the published port is wrong- Consul has it registered as Port 80, when Nomad has it running on 22352. 
```
root@nyc3-nomad1 ~]# dig @127.0.0.1 -p 8600 _website-telescope-frontend-primary-nginx._tcp.service.consul SRV
...
;; ANSWER SECTION:
_website-telescope-frontend-primary-nginx._tcp.service.consul. 0 IN SRV	1 1 80 0a580006.addr.nyc3.consul.
...
```
This is an issue for obvious reasons. The process is running on the right post on the host and is accessible.
```
[root@nyc3-nomad1 ~]# curl 10.234.4.9:22352
<!DOCTYPE html><html lang="en"><head>
```

I'm using driver v0.1.0 under CentOS 8

**Comment by volfco** [comment]
It might be useful for the dockerfile.

```
FROM node:10-alpine as build
WORKDIR /app
COPY . /app
ENV PATH /app/node_modules/.bin:$PATH
# download dependencies and what not
RUN npm install yarn
# build the motherfucker
RUN yarn install
WORKDIR /app/webapp
RUN yarn install
RUN yarn build
RUN apk add git
RUN ["/bin/sh", "/app/utils/build_metadata.sh"]
# RUN ["sh", "/app/utils/load_config.sh"]

FROM nginx:alpine
# TODO we're going to need to change the name of this to something other then example
RUN rm /usr/share/nginx/html/*

COPY --from=build /app/webapp/build /usr/share/nginx/html

COPY utils/nginx.conf /etc/nginx/nginx.conf
COPY utils/entrypoint.sh /entrypoint.sh
EXPOSE 80
CMD ["/bin/sh", "/entrypoint.sh"]
```

**Comment by towe75** [comment]
@volfco  thank you for the report. We will have a look at it.

**Comment by jebas** [comment]
I have the same problem.
Running an nginx container, the nomad health check finds the correct address and port: 10.1.10.13:25101, which is reachable.
However consul has the same service registered at 10.88.0.25:80.
When I check my interfaces, I find one called cni-podman0 which is assigned 10.88.0.1/16.
There is only one container running on the system at this time.  
consul v1.8.4, and nomad v0.12.4.

**Comment by onlyjob** [comment]
Can this be solved by https://www.nomadproject.io/docs/job-specification/service#address_mode e.g. `address_mode = "host"`?

**Comment by towe75** [comment]
Setting address_mode = "host" fixes the problem for me. address_mode default is "auto" but the doc states:

> auto - Allows the driver to determine whether the host or driver address should be used. Defaults to host and only implemented by Docker. If you use a Docker network plugin such as weave, Docker will automatically use its address.

So i guess this fix is to actually use "host" if address_mode is unset (or "auto") ?

**Comment by jebas** [comment]
Thank you.  That resolved my issue nicely.

**Comment by jrasell** [comment]
I'll close this issue as it seems to have been resolved. If this is incorrect, please feel free to reopen this issue, or open another linking here.

**Comment by zandeez** [comment]
Hi guys,

I know this is an old issue but it still exists (somewhat). I'll test the address_mode workaround later, but default behaviour should probably match the documentation.

On another note, the default behaviour reads the mapped port of the container. If you let nomad manage port allocation (port "http" {}) then the port is advertised to consul as port 0 which also doesn't work.
