### ISSUE TITLE
Release prebuilt binaries

### ISSUE THREAD

**Issue by henryx** [hashicorp/nomad-driver-podman#62]
In order to automate installation of the plugin, is useful to release prebuilt binaries in GitHub releases page

**Comment by towe75** [comment]
Hi @henryx 

you can find the binary for the latest release at https://github.com/hashicorp/nomad-driver-podman/releases/tag/v0.1.0
I added a link to the github release page but we should also enhance the readme page.

**Comment by drewbailey** [comment]
HashiCorp releases, including `nomad-driver-podman` can be found on https://releases.hashicorp.com/nomad-driver-podman/
