### ISSUE TITLE
Documentation inconsistencies about ports / port_map

### ISSUE THREAD

**Issue by acuteaura** [hashicorp/nomad-driver-podman#63]
The documentation for this driver refers to the docker driver for networking setup, but the docker driver [has deprecated](https://www.nomadproject.io/docs/drivers/docker#deprecated-port_map-syntax) `port_map` and wants you to reference [ports from the group](https://www.nomadproject.io/docs/drivers/docker#using-the-port-map) `network` stanza in `ports` array. This however does not seem to be implemented in this driver, looking at the config struct.

**Comment by towe75** [comment]
Closed in favor of #70
