### ISSUE TITLE
SELinux labeled volumes on shared filesystem

### ISSUE THREAD

**Issue by fuero** [hashicorp/nomad-driver-podman#65]
OS version: CentOS Linux release 8.2.2004 (Core)
nomad-driver-podman version: git commit 49d9894
nomad version: 0.12.3
podman version: 1.6.4, shipped by CentOS 8
gluster version: 7.7

I got 2 nomad nodes on CentOS 8 set up to mount a gluster volume:

```
gluster.service.local-consul:/gv0 /shared 	glusterfs context=system_u:object_r:container_file_t:s0,selinux 0 0
```
`ls` shows the correct context is applied:
```
# ls /mnt/bar
drwxr-xr-x.  1 root root system_u:object_r:container_file_t:s0    4.0K Sep  7 16:15 bar
```
Running chcon on that filesystem produces an error:

```
# chcon -u system_u -r system_r -t container_file_t -l s0 /mnt/bar
chcon: failed to change context of '/mnt/bar' to ‘system_u:system_r:container_file_t:s0’: Operation not supported
```

Setting `selinuxlabel = "z"` won't let me start *any* container that has volumes on that share, as podman forces relabeling, triggering this error:

```
rpc error: code = Unknown desc = failed to start task, could not start container: io.podman.ErrorOccurred(Reason: relabel failed "/mnt/foo": operation not supported)
```

According to the nomad-driver-podman's docs, `selinuxlabel` is supposed to apply *only* to the local, secrets and alloc mounts:

```
Allows the operator to set a SELinux label to the allocation and task local bind-mounts to containers
```

If the job in question is placed on a filesystem that supports SELinux labels it works fine.

Expected results:

podman not being forced to relabel on a volume that's properly prepared.

**Comment by lgfa29** [comment]
Fixed in #196.
