### ISSUE TITLE
0.1.0 [regression]: invalid reference format oci-archive:app.oci

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad-driver-podman#67]
After upgrading from 0.0.3 my containers don't start any more:

    Couldn't create image: image oci-archive:/mnt/apps/app.oci couldn't be inspected: io.podman.ImageNotFound(Id: oci-archive:/mnt/apps/app.oci, Reason: invalid reference format)

Downgrading back to 0.0.3 fixed the problem...

**Comment by towe75** [comment]
@onlyjob : am i right that you try to reference a local oci archive instead of a repo? I'm surprised that this worked with older versions, i never tested this usecase. 

I will have a look. Surely it has to do with driver.createImage() which was introduced a while ago.

**Comment by towe75** [comment]
@onlyjob : would be nice if you build and run directly from branch i_67.

**Comment by towe75** [comment]
FYI, podman 2.x with API V2 is also broken right now, see https://github.com/containers/podman/issues/6744

**Comment by onlyjob** [comment]
8b84a4fb7ea1d9cac1f94338271624731099bfa6 fixed the issue when applied it on top of 0.1.0. Thank you.

The only new thing required is `/etc/containers/policy.json`.

**Comment by onlyjob** [comment]
> @onlyjob : am i right that you try to reference a local oci archive instead of a repo?

Yes, that's the _only_ way I always used Nomad/driver-podman+Podman. :)

**Comment by towe75** [comment]
@onlyjob thanks for feedback 👍 
Be aware that it might break again in 0.2.0 onwards, we're tracking this via #69
