### ISSUE TITLE
Networking broken without deprecated task level config

### ISSUE THREAD

**Issue by computator** [hashicorp/nomad-driver-podman#70]
As of Nomad 0.12, task level networks and port_map are both deprecated and have been replaced with group level network syntax. The podman driver does not work with the new syntax and requires the (largely undocumented) old syntax and config locations. It appears as if something similar to hashicorp/nomad#8623 needs to be implemented.

#63 seems to be the same issue, but it hasn't gotten much attention due to it's title and wording.

**Comment by towe75** [comment]
@computator thank you for the report. 
This needs to be addressed but let us first finish the podman api v2 compatibility.
I closed #63, it's indeed a duplicate.
