### ISSUE TITLE
Images from a private registry / auth

### ISSUE THREAD

**Issue by mmack** [hashicorp/nomad-driver-podman#71]
It would be great to support the auth flag like the docker driver does: https://www.nomadproject.io/docs/drivers/docker#authentication

**Comment by rodericliu** [comment]
I have been testing this plugin, eveything works fine except the registry authentication. It would be great to have this.

**Comment by towe75** [comment]
Yes, this is a important feature. We will try to add it soon.

**Comment by towe75** [comment]
I checked our options. So far i found that the http API supports only very simple username/password authentication: https://docs.podman.io/en/latest/_static/api.html#operation/libpodImagesPull . I can imagine that we rather want credential helper support for AWS ECR and that alike.

On the other hand: console allows to use credential helpers and docker compatible auth files: https://www.mankier.com/5/containers-auth.json

What's your opinions? Should we start with a simple username/password option and grow it later once there is better API available? It's quite possible that we could use the http API with credential helpers and that only some documentation is missing.

**Comment by towe75** [comment]
It's indeed not possible to configure credential helpers via http API. This means that i will only implement a simple username/password authentication at this time.

**Comment by elimisteve** [comment]
@towe75 Sounds great to me! 👍

**Comment by towe75** [comment]
Implemented via #112

**Comment by kholisrag** [comment]
can we use this method to auth from AWS ECR private repo?
