### ISSUE TITLE
APIVersion field in Version struct not compatible with podman 2.0.5

### ISSUE THREAD

**Issue by nicopap** [hashicorp/nomad-driver-podman#81]
Hello, thank you for this awesome plugin!

First, I know why it's happening and fixing it only involves changing two characters in the README.

### The problem

When running nomad with the podman driver, the podman driver is not activated and I get the following error with `journalctl --unit=nomad.service`: 

```
client.driver_mgr.nomad-driver-podman: Could not get podman info: driver=podman err="json: cannot unmarshal number into Go struct field Version.version.APIVersion of type string"
```

Environment:
* nomad version: 1.0.1
* driver version: 0.2.0
* podman version: 2.0.5
* redhat linux 8

It seems nomad will regardless detect "docker support" when the podman v2 REST socket is activated.

### The reason

Looking at the podman source, the commit containers/podman@c4b49afad, part of the v2.1.0 patch, changed the APIVersion field from an int64 to a string. The `Version` data type in [`api/structs.go`](https://github.com/hashicorp/nomad-driver-podman/blob/master/api/structs.go#L1508) seems to be the corresponding struct in the driver. Since before 2.1.0, the structs were not compatible, and I'm using 2.0.5, this is the source of the error.

### The solution

I don't expect the driver to work with every version of podman, but it would be nice to specify in the README that the minimal working version is 2.1.0 and not 2.x as it currently says. It might be possible to work around it by defining the decoders differently, but I don't know how, and it's not that important. So I recommend updating the doc.

Thank you for your work!

**Comment by towe75** [comment]
@nicopap thank you for your feedback and the detailed report. It will be best to only change the readme given the fact how fast the podman ecosystem is moving forward. You're running RHEL8. Is it possible to install a different version there? I'm curious why nomad would activate the docker support. It's quite different socket locations, IMHO.

**Comment by nicopap** [comment]
Hello. Thank for the quick answer! It's technically possible to install a more recent version of podman, but I'm still on edge about a custom setup, the podman rpm in the appstream dnf repo is still 2.0.5 and I don't want to deviate from that. It's not that pressing for us and I expect to see an update anytime soon, so I'm fine playing the waiting game.

Concerning the docker support: I don't know. I didn't even try to deploy a container with it. Maybe it has to do with the docker CLI?

**Comment by towe75** [comment]
@nicopap podman 3.x arrived few weeks ago.  Podman seems not to maintain older versions, i am not aware of any bugfix releases once a new major is out. How is the situation on RHEL8?

**Comment by nicopap** [comment]
Yeah, I don't think it's a concern anymore.
