### ISSUE TITLE
Driver is not reading correct rootless info

### ISSUE THREAD

**Issue by silvercrown07** [hashicorp/nomad-driver-podman#92]
Hi guys, recently I have been playing with the driver quite some and found some information displayed in nomad ui incorrectly, which is the `rootless` attribute.

Per the current implementation, it's reading from `info.Host.Rootless`: https://github.com/hashicorp/nomad-driver-podman/blob/bf21e157fc5124fbce0a44cae2f6a608b6cd466f/driver.go#L224
However I think it should be `host.security.rootless` per the podman's documentation:  https://docs.podman.io/en/latest/_static/api.html#operation/libpodGetInfo

Please let me know if I got things wrong, and thank you for this awesome driver!

**Comment by towe75** [comment]
Hi @silvercrown07 , thank you for the report. 
Probably it's a podman 3.x change. 
I'll have a look.

**Comment by silvercrown07** [comment]
After some digging i think i found the source:
https://github.com/containers/podman/commit/04b43ccf64dd5166539743b44a95c9921ddc8a9f
File `libpod/define/info.go`

And yes it's a podman 3.x change
